package kube

// ResourceMetadata contains display metadata for a resource type.
type ResourceMetadata struct {
	Emoji     string   // Display emoji for the resource type
	NoRecurse []string // Child types that should not be recursed into during tree building
}

// ResourceTypes maps resource type names to their display metadata.
var ResourceTypes = map[string]ResourceMetadata{
	"certificate":                    {"📜", nil},
	"ciliumclusterwidenetworkpolicy": {"🕸️", []string{"pod"}},
	"ciliumnetworkpolicy":            {"🕸", []string{"service", "pod"}},
	"clusterissuer":                  {"🗝️", nil},
	"clusterrole":                    {"🪪", nil},
	"clusterrolebinding":             {"🔗", []string{"clusterrole", "serviceaccount"}},
	"configmap":                      {"⚙", nil},
	"configmaps":                     {"⚙️", nil},
	"cronjob":                        {"📆", []string{"job"}},
	"csidriver":                      {"🔩", []string{"csinode"}},
	"csinode":                        {"💻", nil},
	"daemonset":                      {"🛰️", nil},
	"deployment":                     {"🚀", nil},
	"endpoints":                      {"📍", []string{"service"}},
	"endpointslice":                  {"📍", []string{"service", "pod"}},
	"gateway":                        {"⛩️", nil},
	"horizontalpodautoscaler":        {"🧬", nil},
	"httproute":                      {"🔄", []string{"service", "gateway"}},
	"ingress":                        {"👉", []string{"service", "certificate"}},
	"ingressclass":                   {"🏷️", nil},
	"issuer":                         {"🔑", []string{"secret", "serviceaccount"}},
	"job":                            {"🔧", nil},
	"limitrange":                     {"📏", nil},
	"networkpolicy":                  {"🧱", []string{"pod"}},
	"node":                           {"🖥️", nil},
	"persistentvolume":               {"💿", []string{"storageclass", "volumeattachment"}},
	"persistentvolumeclaim":          {"📀", []string{"persistentvolume"}},
	"pod":                            {"🫛", []string{"serviceaccount", "configmap", "secret", "persistentvolumeclaim", "service"}},
	"poddisruptionbudget":            {"🛡️", nil},
	"replicaset":                     {"🧩", nil},
	"resourcequota":                  {"📊", nil},
	"role":                           {"🎫", nil},
	"rolebinding":                    {"🔗", []string{"role", "serviceaccount"}},
	"secret":                         {"🔒", nil},
	"secretproviderclass":            {"🔏", []string{"secret"}},
	"service":                        {"🤝", []string{"pod"}},
	"serviceaccount":                 {"👤", []string{"pod"}},
	"statefulset":                    {"🗄️", []string{"persistentvolumeclaim"}},
	"storageclass":                   {"🗂️", []string{"persistentvolume"}},
	"volumeattachment":               {"📎", []string{"persistentvolume"}},

	// Virtual/display-only types
	"accessmodes":                {"🔓", nil},
	"address":                    {"🔌", nil},
	"args":                       {"🗯️", nil},
	"capacity":                   {"📊", nil},
	"certificatecondition":       {"✅", nil},
	"certificatesigningrequest":  {"🎫", nil},
	"certificateusage":           {"📋", nil},
	"ccwnp-egress":               {"👈", []string{"service"}},
	"ccwnp-ingress":              {"👉", nil},
	"cnp-egress":                 {"👈", []string{"service"}},
	"cnp-ingress":                {"👉", nil},
	"command":                    {"⚡", nil},
	"container":                  {"🧊", nil},
	"dnsnames":                   {"🌐", nil},
	"dnspolicy":                  {"🌐", nil},
	"egressrule":                 {"📤", nil},
	"enabledefaultdeny":          {"🚫", nil},
	"endpoint":                   {"🔌", nil},
	"endpointselector":           {"🎯", nil},
	"env":                        {"💬", nil},
	"envars":                     {"🔤", nil},
	"envfrom-configmap":          {"📝", nil},
	"envfrom-secret":             {"🔐", nil},
	"environment":                {"♻️", nil},
	"finalizers":                 {"🔒", nil},
	"flowschema":                 {"📄", nil},
	"fromendpoint":               {"📥", nil},
	"fromentities":               {"🌍", nil},
	"hostipc":                    {"🔧", nil},
	"hostnetwork":                {"🌐", nil},
	"hostpid":                    {"🔧", nil},
	"httproute-ref":              {"🔄", nil},
	"image":                      {"🐋", nil},
	"ingress-route":              {"🔄", nil},
	"ingressrule":                {"📥", nil},
	"issuerref":                  {"🔑", nil},
	"label":                      {"🏷️", nil},
	"labels":                     {"🏷️", nil},
	"lifecycle":                  {"♻️", nil},
	"livenessprobe":              {"💓", nil},
	"mount":                      {"📁", nil},
	"mounts":                     {"📂", nil},
	"namespace":                  {"🗂️", nil},
	"netpol-egress":              {"👈", []string{"service"}},
	"netpol-ingress":             {"👉", nil},
	"networking":                 {"🔀", nil},
	"nodeselector":               {"🎯", nil},
	"notreadyaddress":            {"📵", nil},
	"operator":                   {"🤖", nil},
	"phase":                      {"📍", nil},
	"pod-ref":                    {"🫛", nil},
	"podsecuritycontext":         {"🛡️", nil},
	"port":                       {"⇄", nil},
	"ports":                      {"🔌", nil},
	"priorityclass":              {"⭐", nil},
	"prioritylevelconfiguration": {"📄", nil},
	"qosclass":                   {"📊", nil},
	"readinessprobe":             {"✅", nil},
	"resources":                  {"🔧", nil},
	"restartpolicy":              {"🔄", nil},
	"runtimeclass":               {"🏃", nil},
	"schedule":                   {"⏰", nil},
	"secretkey":                  {"🔑", nil},
	"secretkeys":                 {"🗝️", nil},
	"secretname":                 {"🔒", nil},
	"secrets":                    {"🔒", nil},
	"secretstore":                {"🔐", nil},
	"secrettype":                 {"📋", nil},
	"securitycontext":            {"🛡️", nil},
	"spec":                       {"📑", nil},
	"startupprobe":               {"▶️", nil},
	"storage":                    {"💾", nil},
	"subset":                     {"🔗", nil},
	"tls-cert":                   {"🔒", nil},
	"tls-secret":                 {"🔐", nil},
	"toendpoint":                 {"📤", nil},
	"toentities":                 {"🌍", nil},
	"tofqdn":                     {"🌐", nil},
	"toleration":                 {"🤝", nil},
	"tolerations":                {"🎯", nil},
	"topologyspreadconstraints":  {"📐", nil},
	"toport":                     {"🔌", nil},
	"volumename":                 {"💿", nil},
}

// Loaders maps resource type names to their loader functions.
var Loaders = func() map[string]ResourceLoader {
	l := getLoader
	return map[string]ResourceLoader{
		"certificate":                    LoadCertificate,
		"ciliumclusterwidenetworkpolicy": LoadCiliumClusterwideNetworkPolicy,
		"ciliumnetworkpolicy":            LoadCiliumNetworkPolicy,
		"clusterissuer":                  LoadClusterIssuer,
		"clusterrole":                    l("clusterrole"),
		"clusterrolebinding":             l("clusterrolebinding"),
		"configmap":                      l("configmap"),
		"cronjob":                        l("cronjob"),
		"csidriver":                      l("csidriver"),
		"csinode":                        l("csinode"),
		"daemonset":                      l("daemonset"),
		"deployment":                     l("deployment"),
		"endpoints":                      l("endpoints"),
		"endpointslice":                  l("endpointslice"),
		"gateway":                        LoadGateway,
		"horizontalpodautoscaler":        l("horizontalpodautoscaler"),
		"httproute":                      LoadHTTPRoute,
		"ingress":                        l("ingress"),
		"ingressclass":                   l("ingressclass"),
		"issuer":                         LoadIssuer,
		"job":                            LoadJob,
		"limitrange":                     l("limitrange"),
		"networkpolicy":                  LoadNetworkPolicy,
		"node":                           LoadNode,
		"persistentvolume":               l("persistentvolume"),
		"persistentvolumeclaim":          l("persistentvolumeclaim"),
		"pod":                            LoadPod,
		"poddisruptionbudget":            l("poddisruptionbudget"),
		"replicaset":                     l("replicaset"),
		"resourcequota":                  l("resourcequota"),
		"role":                           l("role"),
		"rolebinding":                    l("rolebinding"),
		"secret":                         LoadSecret,
		"secretproviderclass":            LoadSecretProviderClass,
		"service":                        LoadService,
		"serviceaccount":                 l("serviceaccount"),
		"statefulset":                    l("statefulset"),
		"storageclass":                   l("storageclass"),
		"volumeattachment":               l("volumeattachment"),
	}
}()

// GetResourceEmoji returns the emoji for a given resource type.
func GetResourceEmoji(resourceType string) string {
	if rt, exists := ResourceTypes[resourceType]; exists && rt.Emoji != "" {
		return rt.Emoji
	}
	return "📄"
}
