package kube

// ResourceType contains display metadata for a resource type.
type ResourceType struct {
	Kind       string   // Official Kubernetes Kind name (e.g., "Deployment", "Pod"), empty for virtual types
	Icon       string   // Display emoji for the resource type
	Group      string   // API Group (empty string for core v1, empty for virtual types)
	Version    string   // API Version (e.g., "v1", empty for virtual types)
	Resource   string   // Plural resource name for API calls (e.g., "pods", empty for virtual types)
	Namespaced bool     // Whether resource is namespace-scoped (false for cluster-scoped and virtual types)
	Children   []string // Valid direct child types according to K8s schema (ownership, references)
	NoRecurse  []string // Child types that should not be recursed into during tree building
}

// ResourceTypes maps resource type names to their display metadata.
var ResourceTypes = map[string]ResourceType{
	"certificate":                    {"Certificate", "📜", "cert-manager.io", "v1", "certificates", true, []string{"secret"}, nil},
	"ciliumclusterwidenetworkpolicy": {"CiliumClusterwideNetworkPolicy", "🕸️", "cilium.io", "v2", "ciliumclusterwidenetworkpolicies", false, []string{"pod"}, []string{"pod"}},
	"ciliumnetworkpolicy":            {"CiliumNetworkPolicy", "🕸", "cilium.io", "v2", "ciliumnetworkpolicies", true, []string{"pod", "service"}, []string{"service", "pod"}},
	"clusterissuer":                  {"ClusterIssuer", "🗝️", "cert-manager.io", "v1", "clusterissuers", false, []string{"secret"}, nil},
	"clusterrole":                    {"ClusterRole", "🪪", "rbac.authorization.k8s.io", "v1", "clusterroles", false, nil, nil},
	"clusterrolebinding":             {"ClusterRoleBinding", "🔗", "rbac.authorization.k8s.io", "v1", "clusterrolebindings", false, []string{"clusterrole", "serviceaccount"}, []string{"clusterrole", "serviceaccount"}},
	"configmap":                      {"ConfigMap", "⚙", "", "v1", "configmaps", true, nil, nil},
	"cronjob":                        {"CronJob", "📆", "batch", "v1", "cronjobs", true, []string{"job"}, []string{"job"}},
	"csidriver":                      {"CSIDriver", "🔩", "storage.k8s.io", "v1", "csidrivers", false, []string{"csinode"}, []string{"csinode"}},
	"csinode":                        {"CSINode", "💻", "storage.k8s.io", "v1", "csinodes", false, nil, nil},
	"daemonset":                      {"DaemonSet", "🛰️", "apps", "v1", "daemonsets", true, []string{"pod"}, nil},
	"deployment":                     {"Deployment", "🚀", "apps", "v1", "deployments", true, []string{"replicaset"}, nil},
	"endpoints":                      {"Endpoints", "📍", "", "v1", "endpoints", true, []string{"pod"}, []string{"service"}},
	"endpointslice":                  {"EndpointSlice", "📍", "discovery.k8s.io", "v1", "endpointslices", true, []string{"pod"}, []string{"service", "pod"}},
	"gateway":                        {"Gateway", "⛩️", "gateway.networking.k8s.io", "v1", "gateways", true, []string{"httproute"}, nil},
	"horizontalpodautoscaler":        {"HorizontalPodAutoscaler", "🧬", "autoscaling", "v1", "horizontalpodautoscalers", true, []string{"deployment", "statefulset", "replicaset"}, nil},
	"httproute":                      {"HTTPRoute", "🔄", "gateway.networking.k8s.io", "v1", "httproutes", true, []string{"service", "gateway"}, []string{"service", "gateway"}},
	"ingress":                        {"Ingress", "👉", "networking.k8s.io", "v1", "ingresses", true, []string{"service", "certificate"}, []string{"service", "certificate"}},
	"ingressclass":                   {"IngressClass", "🏷️", "networking.k8s.io", "v1", "ingressclasses", false, nil, nil},
	"issuer":                         {"Issuer", "🔑", "cert-manager.io", "v1", "issuers", true, []string{"secret", "serviceaccount"}, []string{"secret", "serviceaccount"}},
	"job":                            {"Job", "🔧", "batch", "v1", "jobs", true, []string{"pod"}, nil},
	"limitrange":                     {"LimitRange", "📏", "", "v1", "limitranges", true, nil, nil},
	"networkpolicy":                  {"NetworkPolicy", "🧱", "networking.k8s.io", "v1", "networkpolicies", true, []string{"pod"}, []string{"pod"}},
	"node":                           {"Node", "🖥️", "", "v1", "nodes", false, []string{"pod", "csinode"}, nil},
	"persistentvolume":               {"PersistentVolume", "💿", "", "v1", "persistentvolumes", false, []string{"storageclass", "volumeattachment"}, []string{"storageclass", "volumeattachment"}},
	"persistentvolumeclaim":          {"PersistentVolumeClaim", "📀", "", "v1", "persistentvolumeclaims", true, []string{"persistentvolume"}, []string{"persistentvolume"}},
	"pod":                            {"Pod", "🫛", "", "v1", "pods", true, []string{"serviceaccount", "configmap", "secret", "persistentvolumeclaim"}, []string{"serviceaccount", "configmap", "secret", "persistentvolumeclaim", "service"}},
	"poddisruptionbudget":            {"PodDisruptionBudget", "🛡️", "policy", "v1", "poddisruptionbudgets", true, []string{"pod"}, nil},
	"replicaset":                     {"ReplicaSet", "🧩", "apps", "v1", "replicasets", true, []string{"pod"}, nil},
	"resourcequota":                  {"ResourceQuota", "📊", "", "v1", "resourcequotas", true, nil, nil},
	"role":                           {"Role", "🎫", "rbac.authorization.k8s.io", "v1", "roles", true, nil, nil},
	"rolebinding":                    {"RoleBinding", "🔗", "rbac.authorization.k8s.io", "v1", "rolebindings", true, []string{"role", "serviceaccount"}, []string{"role", "serviceaccount"}},
	"secret":                         {"Secret", "🔒", "", "v1", "secrets", true, nil, nil},
	"secretproviderclass":            {"SecretProviderClass", "🔏", "secrets-store.csi.x-k8s.io", "v1", "secretproviderclasses", true, []string{"secret"}, []string{"secret"}},
	"service":                        {"Service", "🤝", "", "v1", "services", true, []string{"pod", "endpoints", "endpointslice"}, []string{"pod"}},
	"serviceaccount":                 {"ServiceAccount", "👤", "", "v1", "serviceaccounts", true, []string{"secret"}, []string{"pod"}},
	"statefulset":                    {"StatefulSet", "🗄️", "apps", "v1", "statefulsets", true, []string{"pod", "persistentvolumeclaim"}, []string{"persistentvolumeclaim"}},
	"storageclass":                   {"StorageClass", "🗂️", "storage.k8s.io", "v1", "storageclasses", false, []string{"persistentvolume"}, []string{"persistentvolume"}},
	"volumeattachment":               {"VolumeAttachment", "📎", "storage.k8s.io", "v1", "volumeattachments", false, []string{"persistentvolume"}, []string{"persistentvolume"}},

	// Virtual/display-only types
	"accessmodes":                {"", "🔓", "", "", "", false, nil, nil},
	"address":                    {"", "🔌", "", "", "", false, nil, nil},
	"args":                       {"", "🗯️", "", "", "", false, nil, nil},
	"capacity":                   {"", "📊", "", "", "", false, nil, nil},
	"certificatecondition":       {"", "✅", "", "", "", false, nil, nil},
	"certificatesigningrequest":  {"", "🎫", "", "", "", false, nil, nil},
	"certificateusage":           {"", "📋", "", "", "", false, nil, nil},
	"ccwnp-egress":               {"", "👈", "", "", "", false, []string{"service"}, []string{"service"}},
	"ccwnp-ingress":              {"", "👉", "", "", "", false, nil, nil},
	"cnp-egress":                 {"", "👈", "", "", "", false, []string{"service"}, []string{"service"}},
	"cnp-ingress":                {"", "👉", "", "", "", false, nil, nil},
	"command":                    {"", "⚡", "", "", "", false, nil, nil},
	"container":                  {"", "🧊", "", "", "", false, []string{"image", "ports", "environment", "mounts", "resources", "livenessprobe", "readinessprobe", "startupprobe", "securitycontext"}, nil},
	"configmaps":                 {"", "⚙️", "", "", "", false, []string{"configmap"}, nil},
	"dnsnames":                   {"", "🌐", "", "", "", false, nil, nil},
	"dnspolicy":                  {"", "🌐", "", "", "", false, nil, nil},
	"egressrule":                 {"", "📤", "", "", "", false, nil, nil},
	"enabledefaultdeny":          {"", "🚫", "", "", "", false, nil, nil},
	"endpoint":                   {"", "🔌", "", "", "", false, []string{"pod-ref"}, nil},
	"endpointselector":           {"", "🎯", "", "", "", false, nil, nil},
	"env":                        {"", "💬", "", "", "", false, []string{"configmap", "secret"}, nil},
	"envars":                     {"", "🔤", "", "", "", false, []string{"env"}, nil},
	"envfrom-configmap":          {"", "📝", "", "", "", false, []string{"configmap"}, nil},
	"envfrom-secret":             {"", "🔐", "", "", "", false, []string{"secret"}, nil},
	"environment":                {"", "♻️", "", "", "", false, []string{"env"}, nil},
	"finalizers":                 {"", "🔒", "", "", "", false, nil, nil},
	"flowschema":                 {"", "📄", "", "", "", false, nil, nil},
	"fromendpoint":               {"", "📥", "", "", "", false, []string{"toport"}, nil},
	"fromentities":               {"", "🌍", "", "", "", false, nil, nil},
	"hostipc":                    {"", "🔧", "", "", "", false, nil, nil},
	"hostnetwork":                {"", "🌐", "", "", "", false, nil, nil},
	"hostpid":                    {"", "🔧", "", "", "", false, nil, nil},
	"httproute-ref":              {"", "🔄", "", "", "", false, []string{"httproute"}, nil},
	"image":                      {"", "🐋", "", "", "", false, nil, nil},
	"ingress-route":              {"", "🔄", "", "", "", false, []string{"service"}, nil},
	"ingressrule":                {"", "📥", "", "", "", false, []string{"service"}, nil},
	"issuerref":                  {"", "🔑", "", "", "", false, []string{"issuer", "clusterissuer"}, nil},
	"label":                      {"", "🏷️", "", "", "", false, nil, nil},
	"labels":                     {"", "🏷️", "", "", "", false, nil, nil},
	"lifecycle":                  {"", "♻️", "", "", "", false, nil, nil},
	"livenessprobe":              {"", "💓", "", "", "", false, nil, nil},
	"mount":                      {"", "📁", "", "", "", false, []string{"configmap", "secret", "persistentvolumeclaim", "storage"}, nil},
	"mounts":                     {"", "📂", "", "", "", false, []string{"mount"}, nil},
	"namespace":                  {"", "🗂️", "", "", "", false, nil, nil},
	"netpol-egress":              {"", "👈", "", "", "", false, []string{"service"}, []string{"service"}},
	"netpol-ingress":             {"", "👉", "", "", "", false, nil, nil},
	"networking":                 {"", "🔀", "", "", "", false, nil, nil},
	"nodeselector":               {"", "🎯", "", "", "", false, nil, nil},
	"notreadyaddress":            {"", "📵", "", "", "", false, nil, nil},
	"operator":                   {"", "🤖", "", "", "", false, nil, nil},
	"phase":                      {"", "📍", "", "", "", false, nil, nil},
	"pod-ref":                    {"", "🫛", "", "", "", false, nil, nil},
	"podsecuritycontext":         {"", "🛡️", "", "", "", false, nil, nil},
	"port":                       {"", "⇄", "", "", "", false, nil, nil},
	"ports":                      {"", "🔌", "", "", "", false, []string{"port"}, nil},
	"priorityclass":              {"", "⭐", "", "", "", false, nil, nil},
	"prioritylevelconfiguration": {"", "📄", "", "", "", false, nil, nil},
	"qosclass":                   {"", "📊", "", "", "", false, nil, nil},
	"readinessprobe":             {"", "✅", "", "", "", false, nil, nil},
	"resources":                  {"", "🔧", "", "", "", false, nil, nil},
	"restartpolicy":              {"", "🔄", "", "", "", false, nil, nil},
	"runtimeclass":               {"", "🏃", "", "", "", false, nil, nil},
	"schedule":                   {"", "⏰", "", "", "", false, nil, nil},
	"secretkey":                  {"", "🔑", "", "", "", false, nil, nil},
	"secretkeys":                 {"", "🗝️", "", "", "", false, nil, nil},
	"secretname":                 {"", "🔒", "", "", "", false, nil, nil},
	"secrets":                    {"", "🔒", "", "", "", false, []string{"secret"}, nil},
	"secretstore":                {"", "🔐", "", "", "", false, []string{"secretproviderclass", "secret", "mount"}, nil},
	"secrettype":                 {"", "📋", "", "", "", false, nil, nil},
	"securitycontext":            {"", "🛡️", "", "", "", false, nil, nil},
	"spec":                       {"", "📑", "", "", "", false, []string{"container"}, nil},
	"startupprobe":               {"", "▶️", "", "", "", false, nil, nil},
	"storage":                    {"", "💾", "", "", "", false, []string{"mount"}, nil},
	"subset":                     {"", "🔗", "", "", "", false, []string{"address", "port"}, nil},
	"tls-cert":                   {"", "🔒", "", "", "", false, nil, nil},
	"tls-secret":                 {"", "🔐", "", "", "", false, []string{"secret"}, nil},
	"toendpoint":                 {"", "📤", "", "", "", false, []string{"toport"}, nil},
	"toentities":                 {"", "🌍", "", "", "", false, nil, nil},
	"tofqdn":                     {"", "🌐", "", "", "", false, nil, nil},
	"toleration":                 {"", "🤝", "", "", "", false, nil, nil},
	"tolerations":                {"", "🎯", "", "", "", false, nil, nil},
	"topologyspreadconstraints":  {"", "📐", "", "", "", false, nil, nil},
	"toport":                     {"", "🔌", "", "", "", false, nil, nil},
	"volumename":                 {"", "💿", "", "", "", false, nil, nil},
}

// Loaders maps resource type names to their loader functions.
var Loaders = func() map[string]ResourceLoader {
	l := getLoader
	return map[string]ResourceLoader{
		"certificate":                    LoadCertificate,
		"ciliumclusterwidenetworkpolicy": LoadCiliumClusterwideNetworkPolicy,
		"ciliumnetworkpolicy":            LoadCiliumNetworkPolicy,
		"clusterissuer":                  LoadClusterIssuer,
		"clusterrole":                    l("clusterrole"),
		"clusterrolebinding":             l("clusterrolebinding"),
		"configmap":                      l("configmap"),
		"cronjob":                        l("cronjob"),
		"csidriver":                      l("csidriver"),
		"csinode":                        l("csinode"),
		"daemonset":                      l("daemonset"),
		"deployment":                     l("deployment"),
		"endpoints":                      l("endpoints"),
		"endpointslice":                  l("endpointslice"),
		"gateway":                        LoadGateway,
		"horizontalpodautoscaler":        l("horizontalpodautoscaler"),
		"httproute":                      LoadHTTPRoute,
		"ingress":                        l("ingress"),
		"ingressclass":                   l("ingressclass"),
		"issuer":                         LoadIssuer,
		"job":                            LoadJob,
		"limitrange":                     l("limitrange"),
		"networkpolicy":                  LoadNetworkPolicy,
		"node":                           LoadNode,
		"persistentvolume":               l("persistentvolume"),
		"persistentvolumeclaim":          l("persistentvolumeclaim"),
		"pod":                            LoadPod,
		"poddisruptionbudget":            l("poddisruptionbudget"),
		"replicaset":                     l("replicaset"),
		"resourcequota":                  l("resourcequota"),
		"role":                           l("role"),
		"rolebinding":                    l("rolebinding"),
		"secret":                         LoadSecret,
		"secretproviderclass":            LoadSecretProviderClass,
		"service":                        LoadService,
		"serviceaccount":                 l("serviceaccount"),
		"statefulset":                    l("statefulset"),
		"storageclass":                   l("storageclass"),
		"volumeattachment":               l("volumeattachment"),
	}
}()

// GetResourceEmoji returns the emoji for a given resource type.
func GetResourceEmoji(resourceType string) string {
	if rt, exists := ResourceTypes[resourceType]; exists && rt.Icon != "" {
		return rt.Icon
	}
	return "📄"
}
