package kube

// ResourceType contains display metadata for a resource type.
type ResourceType struct {
	Icon      string   // Display emoji for the resource type
	Children  []string // Valid direct child types according to K8s schema (ownership, references)
	NoRecurse []string // Child types that should not be recursed into during tree building
}

// ResourceTypes maps resource type names to their display metadata.
var ResourceTypes = map[string]ResourceType{
	"certificate":                    {"📜", []string{"secret"}, nil},
	"ciliumclusterwidenetworkpolicy": {"🕸️", []string{"pod"}, []string{"pod"}},
	"ciliumnetworkpolicy":            {"🕸", []string{"pod", "service"}, []string{"service", "pod"}},
	"clusterissuer":                  {"🗝️", []string{"secret"}, nil},
	"clusterrole":                    {"🪪", nil, nil},
	"clusterrolebinding":             {"🔗", []string{"clusterrole", "serviceaccount"}, []string{"clusterrole", "serviceaccount"}},
	"configmap":                      {"⚙", nil, nil},
	"cronjob":                        {"📆", []string{"job"}, []string{"job"}},
	"csidriver":                      {"🔩", []string{"csinode"}, []string{"csinode"}},
	"csinode":                        {"💻", nil, nil},
	"daemonset":                      {"🛰️", []string{"pod"}, nil},
	"deployment":                     {"🚀", []string{"replicaset"}, nil},
	"endpoints":                      {"📍", []string{"pod"}, []string{"service"}},
	"endpointslice":                  {"📍", []string{"pod"}, []string{"service", "pod"}},
	"gateway":                        {"⛩️", []string{"httproute"}, nil},
	"horizontalpodautoscaler":        {"🧬", []string{"deployment", "statefulset", "replicaset"}, nil},
	"httproute":                      {"🔄", []string{"service", "gateway"}, []string{"service", "gateway"}},
	"ingress":                        {"👉", []string{"service", "certificate"}, []string{"service", "certificate"}},
	"ingressclass":                   {"🏷️", nil, nil},
	"issuer":                         {"🔑", []string{"secret", "serviceaccount"}, []string{"secret", "serviceaccount"}},
	"job":                            {"🔧", []string{"pod"}, nil},
	"limitrange":                     {"📏", nil, nil},
	"networkpolicy":                  {"🧱", []string{"pod"}, []string{"pod"}},
	"node":                           {"🖥️", []string{"pod", "csinode"}, nil},
	"persistentvolume":               {"💿", []string{"storageclass", "volumeattachment"}, []string{"storageclass", "volumeattachment"}},
	"persistentvolumeclaim":          {"📀", []string{"persistentvolume"}, []string{"persistentvolume"}},
	"pod":                            {"🫛", []string{"serviceaccount", "configmap", "secret", "persistentvolumeclaim"}, []string{"serviceaccount", "configmap", "secret", "persistentvolumeclaim", "service"}},
	"poddisruptionbudget":            {"🛡️", []string{"pod"}, nil},
	"replicaset":                     {"🧩", []string{"pod"}, nil},
	"resourcequota":                  {"📊", nil, nil},
	"role":                           {"🎫", nil, nil},
	"rolebinding":                    {"🔗", []string{"role", "serviceaccount"}, []string{"role", "serviceaccount"}},
	"secret":                         {"🔒", nil, nil},
	"secretproviderclass":            {"🔏", []string{"secret"}, []string{"secret"}},
	"service":                        {"🤝", []string{"pod", "endpoints", "endpointslice"}, []string{"pod"}},
	"serviceaccount":                 {"👤", []string{"secret"}, []string{"pod"}},
	"statefulset":                    {"🗄️", []string{"pod", "persistentvolumeclaim"}, []string{"persistentvolumeclaim"}},
	"storageclass":                   {"🗂️", []string{"persistentvolume"}, []string{"persistentvolume"}},
	"volumeattachment":               {"📎", []string{"persistentvolume"}, []string{"persistentvolume"}},

	// Virtual/display-only types
	"accessmodes":                {"🔓", nil, nil},
	"address":                    {"🔌", nil, nil},
	"args":                       {"🗯️", nil, nil},
	"capacity":                   {"📊", nil, nil},
	"certificatecondition":       {"✅", nil, nil},
	"certificatesigningrequest":  {"🎫", nil, nil},
	"certificateusage":           {"📋", nil, nil},
	"ccwnp-egress":               {"👈", []string{"service"}, []string{"service"}},
	"ccwnp-ingress":              {"👉", nil, nil},
	"cnp-egress":                 {"👈", []string{"service"}, []string{"service"}},
	"cnp-ingress":                {"👉", nil, nil},
	"command":                    {"⚡", nil, nil},
	"container":                  {"🧊", []string{"image", "ports", "environment", "mounts", "resources", "livenessprobe", "readinessprobe", "startupprobe", "securitycontext"}, nil},
	"configmaps":                 {"⚙️", []string{"configmap"}, nil},
	"dnsnames":                   {"🌐", nil, nil},
	"dnspolicy":                  {"🌐", nil, nil},
	"egressrule":                 {"📤", nil, nil},
	"enabledefaultdeny":          {"🚫", nil, nil},
	"endpoint":                   {"🔌", []string{"pod-ref"}, nil},
	"endpointselector":           {"🎯", nil, nil},
	"env":                        {"💬", []string{"configmap", "secret"}, nil},
	"envars":                     {"🔤", []string{"env"}, nil},
	"envfrom-configmap":          {"📝", []string{"configmap"}, nil},
	"envfrom-secret":             {"🔐", []string{"secret"}, nil},
	"environment":                {"♻️", []string{"env"}, nil},
	"finalizers":                 {"🔒", nil, nil},
	"flowschema":                 {"📄", nil, nil},
	"fromendpoint":               {"📥", []string{"toport"}, nil},
	"fromentities":               {"🌍", nil, nil},
	"hostipc":                    {"🔧", nil, nil},
	"hostnetwork":                {"🌐", nil, nil},
	"hostpid":                    {"🔧", nil, nil},
	"httproute-ref":              {"🔄", []string{"httproute"}, nil},
	"image":                      {"🐋", nil, nil},
	"ingress-route":              {"🔄", []string{"service"}, nil},
	"ingressrule":                {"📥", []string{"service"}, nil},
	"issuerref":                  {"🔑", []string{"issuer", "clusterissuer"}, nil},
	"label":                      {"🏷️", nil, nil},
	"labels":                     {"🏷️", nil, nil},
	"lifecycle":                  {"♻️", nil, nil},
	"livenessprobe":              {"💓", nil, nil},
	"mount":                      {"📁", []string{"configmap", "secret", "persistentvolumeclaim", "storage"}, nil},
	"mounts":                     {"📂", []string{"mount"}, nil},
	"namespace":                  {"🗂️", nil, nil},
	"netpol-egress":              {"👈", []string{"service"}, []string{"service"}},
	"netpol-ingress":             {"👉", nil, nil},
	"networking":                 {"🔀", nil, nil},
	"nodeselector":               {"🎯", nil, nil},
	"notreadyaddress":            {"📵", nil, nil},
	"operator":                   {"🤖", nil, nil},
	"phase":                      {"📍", nil, nil},
	"pod-ref":                    {"🫛", nil, nil},
	"podsecuritycontext":         {"🛡️", nil, nil},
	"port":                       {"⇄", nil, nil},
	"ports":                      {"🔌", []string{"port"}, nil},
	"priorityclass":              {"⭐", nil, nil},
	"prioritylevelconfiguration": {"📄", nil, nil},
	"qosclass":                   {"📊", nil, nil},
	"readinessprobe":             {"✅", nil, nil},
	"resources":                  {"🔧", nil, nil},
	"restartpolicy":              {"🔄", nil, nil},
	"runtimeclass":               {"🏃", nil, nil},
	"schedule":                   {"⏰", nil, nil},
	"secretkey":                  {"🔑", nil, nil},
	"secretkeys":                 {"🗝️", nil, nil},
	"secretname":                 {"🔒", nil, nil},
	"secrets":                    {"🔒", []string{"secret"}, nil},
	"secretstore":                {"🔐", []string{"secretproviderclass", "secret", "mount"}, nil},
	"secrettype":                 {"📋", nil, nil},
	"securitycontext":            {"🛡️", nil, nil},
	"spec":                       {"📑", []string{"container"}, nil},
	"startupprobe":               {"▶️", nil, nil},
	"storage":                    {"💾", []string{"mount"}, nil},
	"subset":                     {"🔗", []string{"address", "port"}, nil},
	"tls-cert":                   {"🔒", nil, nil},
	"tls-secret":                 {"🔐", []string{"secret"}, nil},
	"toendpoint":                 {"📤", []string{"toport"}, nil},
	"toentities":                 {"🌍", nil, nil},
	"tofqdn":                     {"🌐", nil, nil},
	"toleration":                 {"🤝", nil, nil},
	"tolerations":                {"🎯", nil, nil},
	"topologyspreadconstraints":  {"📐", nil, nil},
	"toport":                     {"🔌", nil, nil},
	"volumename":                 {"💿", nil, nil},
}

// Loaders maps resource type names to their loader functions.
var Loaders = func() map[string]ResourceLoader {
	l := getLoader
	return map[string]ResourceLoader{
		"certificate":                    LoadCertificate,
		"ciliumclusterwidenetworkpolicy": LoadCiliumClusterwideNetworkPolicy,
		"ciliumnetworkpolicy":            LoadCiliumNetworkPolicy,
		"clusterissuer":                  LoadClusterIssuer,
		"clusterrole":                    l("clusterrole"),
		"clusterrolebinding":             l("clusterrolebinding"),
		"configmap":                      l("configmap"),
		"cronjob":                        l("cronjob"),
		"csidriver":                      l("csidriver"),
		"csinode":                        l("csinode"),
		"daemonset":                      l("daemonset"),
		"deployment":                     l("deployment"),
		"endpoints":                      l("endpoints"),
		"endpointslice":                  l("endpointslice"),
		"gateway":                        LoadGateway,
		"horizontalpodautoscaler":        l("horizontalpodautoscaler"),
		"httproute":                      LoadHTTPRoute,
		"ingress":                        l("ingress"),
		"ingressclass":                   l("ingressclass"),
		"issuer":                         LoadIssuer,
		"job":                            LoadJob,
		"limitrange":                     l("limitrange"),
		"networkpolicy":                  LoadNetworkPolicy,
		"node":                           LoadNode,
		"persistentvolume":               l("persistentvolume"),
		"persistentvolumeclaim":          l("persistentvolumeclaim"),
		"pod":                            LoadPod,
		"poddisruptionbudget":            l("poddisruptionbudget"),
		"replicaset":                     l("replicaset"),
		"resourcequota":                  l("resourcequota"),
		"role":                           l("role"),
		"rolebinding":                    l("rolebinding"),
		"secret":                         LoadSecret,
		"secretproviderclass":            LoadSecretProviderClass,
		"service":                        LoadService,
		"serviceaccount":                 l("serviceaccount"),
		"statefulset":                    l("statefulset"),
		"storageclass":                   l("storageclass"),
		"volumeattachment":               l("volumeattachment"),
	}
}()

// GetResourceEmoji returns the emoji for a given resource type.
func GetResourceEmoji(resourceType string) string {
	if rt, exists := ResourceTypes[resourceType]; exists && rt.Icon != "" {
		return rt.Icon
	}
	return "📄"
}
