name: Build and Push Docker Image

on:
  push:
    tags: ['v*']

jobs:
  build:
    concurrency:
      group: docker-${{ github.ref }}
      cancel-in-progress: true
    uses: karloie/gh-workflows/.github/workflows/docker.yml@main
    with:
      image: karloie/kompass
      event_name: ${{ github.event_name }}
      tag: ${{ inputs.tag }}
      tool_ref: main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
