name: Build and Publish GoReleaser Artifacts

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  goreleaser:
    concurrency:
      group: goreleaser-${{ github.ref }}
      cancel-in-progress: false
    uses: karloie/gh-workflows/.github/workflows/goreleaser.yml@main
    with:
      event_name: ${{ github.event_name }}
      tag: ${{ inputs.tag }}
      publish: ${{ inputs.publish }}
      tool_ref: main
    secrets:
      HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}